name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint Check
        run: |
          make lint
      - uses: psf/black@stable
        with:
          src: "./goblet_workflows"
          version: "23.1.0"

  Test:
    runs-on: ubuntu-latest
    needs: Lint
    strategy:
      matrix:
        python-version: ['3.10']
    name: Test Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest & goblet_workflows
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install requests-mock
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          export PYTHONPATH=$(pwd)
          coverage run -m pytest goblet_workflows/tests;
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1